### ISSUE TITLE
Vertexing produces propagation errors

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#1345]
During propagation to the vertex position, the propagation seems to get stuck.

@andiwand has observed 

```
Step failed with EigenStepperError:3: Step size adjustment exceeds maximum trials
```

which seems to be the accurracy correction flip flopping between two step sizes and failing to converge.

In addition to this error, ATLAS observes an error

```
18:35:26 18:35:26    HelTrkLinPro   WARNING   Pixel::Barrel | No further navigation action, proceed to target. This is very likely an error
```

in minbias events with low-pt in reprocessing ([JIRA ticket](https://its.cern.ch/jira/browse/ATLASRECTS-7148))

**Comment by andiwand** [comment]
see https://github.com/acts-project/acts/pull/1299 if you want to reproduce this issue

**Comment by andiwand** [comment]
somehow we end up with a perigee inside the pixel barrel

´´´
intersect Acts::PerigeeSurface:
     Center position  (x, y, z) = (20.3294226, -79.1081599, 169.4577863) from pos 0.002635 0.000678 0.116209 with direction  0.108395 -0.421310  0.900416 navDir backward
StandardAborters: setStepSize navDir backward distance -187.753649
ConstrainedStep ( -∞,  -∞,  -∞,  -∞ ) update value 187.753649 original direction backward
17:49:50    HelTrkLinPro   ERROR     Step failed with EigenStepperError:3: Step size adjustment exceeds maximum trials
´´´

to me it looks like every time the perigee is not inside the beam pip we crash

[debug.log](https://github.com/acts-project/acts/files/9191398/debug.log)

**Comment by asalzburger** [comment]
That's exactly what I was referring to in the JIRA. The perigee is in fact allowed to be in the pixel barrel - we should make sure the shorter catches this and ends the propagation accordingly.

**Comment by andiwand** [comment]
here an extreme case

```
intersect Acts::PerigeeSurface:
     Center position  (x, y, z) = (2998.3168793, 474.3935881, -3004.7428436) from pos -0.007314  0.046232 -0.015186 with direction  0.701984  0.111057 -0.703481 navDir backward
StandardAborters: setStepSize navDir backward distance -4271.215506
ConstrainedStep ( -∞,  -∞,  -∞,  -∞ ) update value 4271.215506 original direction backward
08:34:00    HelTrkLinPro   ERROR     Step failed with EigenStepperError:3: Step size adjustment exceeds maximum trials
```

**Comment by paulgessinger** [comment]
After discussion with @andiwand and @asalzburger, our theory is that the underlying issue is that the vertex seeding gives initial vertex positions that are outside the beampipe volume. While this might be physically plausible in some cases, in the current state, we think the vertexing tries to hit these large radius targets by going **backwards** while already being close to the detector center, which either results in the navigation failing or the step size adjustment failing. This will have to be validated.

- [ ] @andiwand will add extra checks and a unit test to catch the unusable `+- inf` step size that tiggers the flip-flop in the step size adjustment
- [ ] @asalzburger will try to add a unit-test reproducer for the `No further navigation action` WARNING
- [ ] @paulgessinger will try to reproduce the `No further navigation action` in the ACTS KF refitting code in ATLAS.

**Comment by andiwand** [comment]
the overall effect with the `ConstrainedStep`. the direction is flipping back and forth

I am starting to wonder if `ConstrainedStep` should be allowed to change the direction https://github.com/acts-project/acts/blob/main/Core/include/Acts/Propagator/ConstrainedStep.hpp#L90. if so it should flip the sign of `max`

```
intersect Acts::PerigeeSurface:
     Center position  (x, y, z) = (-47.5192262, -87.0943331, 42.2686216) from pos  0.036648 -0.020023  0.003728 with direction -0.441092 -0.807337  0.391976 navDir backward
StandardAborters: setStepSize navDir backward distance -107.844601
ConstrainedStep ( -∞,  -∞,  -∞,  -∞ ) update value 107.844601 original direction backward
EigenStepper: pre step size ( -∞,  -∞, 107.845,  -∞ ) direction backward scaling 0.823988
EigenStepper: post step size (88.8626,  -∞, 107.845,  -∞ ) direction forward scaling 0.823988
EigenStepper: pre step size (88.8626,  -∞, 107.845,  -∞ ) direction forward scaling 0.250000
EigenStepper: post step size (-4.49423e+307,  -∞, 107.845,  -∞ ) direction backward scaling 0.250000
EigenStepper: pre step size (-4.49423e+307,  -∞, 107.845,  -∞ ) direction backward scaling 0.823988
EigenStepper: post step size (88.8626,  -∞, 107.845,  -∞ ) direction forward scaling 0.823988
EigenStepper: pre step size (88.8626,  -∞, 107.845,  -∞ ) direction forward scaling 0.250000
```

**Comment by paulgessinger** [comment]
I believe the WARNING should already be fixed with #1101 #1107 and #1115.

**Comment by andiwand** [comment]
I believe I was able to fix the `+/- max` problem but the underlying navigation problem remains. When I changed the `ConstraintedStep` more aggressively the vertexing worked but I guess it was only a work around.

What I saw is that the `ConstrainedStep` is set to backwards propagation `(-∞,  -∞,  -∞,  -∞)` but the `SurfaceReached` aborter will set the target in the forwards direction `-∞,  -∞, 107.845,  -∞`. If the `EigenStepper` cannot reach its accuracy with `107.845` it will try to reduce the step size by scaling it down to `88.8626` and we end up with `(88.8626,  -∞, 107.845,  -∞ )`. Since we are in back propagation the `ConstrainedStep` is required to give us the biggest value which is `107.845` and the whole thing loops until timeout.

The "fix" I tried was to not return the biggest value but the one which is closest to 0 which allows the `EigenStepper` to converge. It worked for the vertexing and I guess the vertex seeds in the pixel barrel where then just discarded. But at the same time it broke a bunch of unit tests so I guess that approach is not valid.

**Comment by andiwand** [comment]
should we close after putting #1363 in?

**Comment by AJPfleger** [comment]
What is the status on this?

I see in https://github.com/acts-project/acts/issues/1345#issuecomment-1196397376 two points, that maybe need to be done.

Was this sufficiently resolved by:
- https://github.com/acts-project/acts/pull/1363 ?

**Comment by andiwand** [comment]
I think I haven't seen this error in a long time
